version: '3.8'

services:

  mongoUserTest:
    container_name: mongoUserTest
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    container_name: mongo-usertest-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongoUserTest
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

      ME_CONFIG_MONGODB_URL: mongodb://admin:password@localhost:27017/
    depends_on:
      - mongoUserTest